# Form implementation generated from reading ui file 'src/logjam/ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(879, 527)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 851, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 879, 37))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFilter = QtWidgets.QMenu(parent=self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionOpen.setFont(font)
        self.actionOpen.setObjectName("actionOpen")
        self.actionOpen_Filter = QtGui.QAction(parent=MainWindow)
        self.actionOpen_Filter.setObjectName("actionOpen_Filter")
        self.actionNew_Filter = QtGui.QAction(parent=MainWindow)
        self.actionNew_Filter.setObjectName("actionNew_Filter")
        self.actionEdit_Current_Filter = QtGui.QAction(parent=MainWindow)
        self.actionEdit_Current_Filter.setObjectName("actionEdit_Current_Filter")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(parent=MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.menuFile.addAction(self.actionOpen)
        self.menuFilter.addAction(self.actionOpen_Filter)
        self.menuFilter.addAction(self.actionNew_Filter)
        self.menuFilter.addAction(self.actionEdit_Current_Filter)
        self.menuFilter.addAction(self.actionSave_As)
        self.menuFilter.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFilter.setTitle(_translate("MainWindow", "Filter"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_Filter.setText(_translate("MainWindow", "Open Filter"))
        self.actionNew_Filter.setText(_translate("MainWindow", "New Filter"))
        self.actionEdit_Current_Filter.setText(_translate("MainWindow", "Edit Current Filter"))
        self.actionSave.setText(_translate("MainWindow", "Save Filter"))
        self.actionSave_As.setText(_translate("MainWindow", "Save Filter As"))
